version: "3.9"

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10000:3000"
    volumes:
      - type: bind
        source: ./app
        target: /usr/src/app
    environment:
      - NODE_ENV=development
    # command: sh -c "cd react-app && yarn start"
    stdin_open: true

